### ISSUE TITLE
State that the code will likely work for the SG500 drone, too

### ISSUE THREAD

**Issue by Windfisch** [r3dapple/JJRC-Blue-Crab-Remote-Control#1]
Hi,

while reverse-engineering my [SG500](https://aliexpress.com/item/32958006579.html?spm=a2g0x.search0302.3.28.7c57375avQAx1L&ws_ab_test=searchweb0_0%2Csearchweb201602_0_453_454_10618_536_317_537_319_10059_10696_10084_10083_10547_10304_10821_10843_10887_10307_321_10548_322_10065_10068_10103_10884_10820_10302%2Csearchweb201603_0%2CppcSwitch_0&algo_pvid=927328e0-c54b-4c60-93e4-cd2ccd738528&algo_expid=927328e0-c54b-4c60-93e4-cd2ccd738528-3) drone, I found this repo.
From what I know about the SG500 so far, your code seems pretty much compatible with it.

To ease others who might look for this, you might want to state in the Readme that this repo likely works for the SG500 and other cheap china copters.

Likely, an indicator is that on port 23 (telnet), there's a "Thread OS"-shell, a chinese RTOS. Can you check with your drone please :)?

Thanks for the work,
Windfisch

**Comment by r3dapple** [comment]
I just noticed this issue, I will include the extra info in the Readme. Thanks for your contribution :)
